### ISSUE TITLE
follow buildstep and rebase image on gliderlabs/herokuish

### ISSUE THREAD

**Issue by rvalyi** [fgrehm/devstep#102]
Hello, now instead of buildstep, herokuish tend to be used by open source Paas platforms. I think it would be cool to follow and move the base image to gliderlabs/herokuish. This should change very little, from what I understood it's Heroku who made the move to provide its base stack as a well maintained Docker image.
See https://github.com/gliderlabs/herokuish

**Comment by fgrehm** [comment]
Devstep is [already being based off of `heroku/cedar:14`](https://github.com/fgrehm/devstep/blob/d8e3b604fa34b0a2f9db6ef64401f54ce806b711/Dockerfile#L1) which is the base image provided by heroku and [used by herokuish](https://github.com/gliderlabs/herokuish/blob/dbab129ffdddcb3f0243af936bb4ee9fdb521046/Dockerfile#L1) as well :-)

**Comment by rvalyi** [comment]
right, perfect, sorry for the confusion.
