### ISSUE TITLE
Port back to docker-machine?

### ISSUE THREAD

**Issue by blaggacao** [fgrehm/devstep#104]
@fgrehm 

As @rvalyi pointed me to your tooling on our mailing list, have you thought of porting back your best practices in this field (or some subset of it) to docker-machine (which already works with TCP and so works on windows) in a kind of `docker-machine hack` command. Probably done in the form of a design proposal?

Close this at will. thx.

**Comment by fgrehm** [comment]
Sorry, unfortunately I haven't given much thought to this yet... I'm still the only one on my team that uses Docker for development (or any type of virtualized dev environment) and I personally use Linux as my main OS, so I don't know much about docker-machine to help with this :disappointed: 

What I've been thinking lately was to try to leverage [libcompose](https://github.com/docker/libcompose/) for devstep's CLI, but haven't made much progress with that yet as I have been focusing heavily on going the last mile to get my university degree :grin: 

Do you have any idea about things that are in use by Devstep which might be interesting to docker-machine? I personally only used it for spinning up cloud VMs, not for local development

**Comment by blaggacao** [comment]
I think you have gathered a lot of best practices INSIDE the docker, that are very specific to the dev-environment use case, I'm unaware of other tools, but this consolidation of knowledge I think would definitely be valuable on a broader scope. 

docker-machine is the tool to get docker working on windows and osx via the boot2docker.iso on a virtualbox VM. There is no other way. But the good thing is, it is transparent and has moved to a new api with the latest release.

But as compose is now available on windows to and works transparently, I think there are ways to not to bother as long as you would implement the `libcompose` api transparently.

I;m currently trying to get hold on a similar project, where I try to take care of the `git` (and folder structure) part by trying to re-implement the `go get` command adapted to the software project, I'm working on. Ideally, there is a better alternative. Do you have probably an better idea?

https://github.com/blaggacao/vodoo

**Comment by blaggacao** [comment]
times have changed with native docker client for windows and osx, which makes the underlying need of my request somewhat obsolete
